/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { destinationsGetDestinationByIdDestinationsDestinationIdGet } from "../../funcs/destinationsGetDestinationByIdDestinationsDestinationIdGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .GetDestinationByIdDestinationsDestinationIdGetRequest$inboundSchema,
};

export const tool$destinationsGetDestinationByIdDestinationsDestinationIdGet:
  ToolDefinition<typeof args> = {
    name: "destinations-get-destination-by-id-destinations-destination-id-get",
    description: `Get Destination By Id

Retrieve details of a specific holiday destination by its ID.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await destinationsGetDestinationByIdDestinationsDestinationIdGet(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
