/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { destinationsUpdateDestinationDestinationsDestinationIdPut } from "../../funcs/destinationsUpdateDestinationDestinationsDestinationIdPut.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .UpdateDestinationDestinationsDestinationIdPutRequest$inboundSchema,
};

export const tool$destinationsUpdateDestinationDestinationsDestinationIdPut:
  ToolDefinition<typeof args> = {
    name: "destinations-update-destination-destinations-destination-id-put",
    description: `Update Destination

Update details of a specific holiday destination by its ID.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await destinationsUpdateDestinationDestinationsDestinationIdPut(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
