/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { destinationsDeleteDestinationDestinationsDestinationIdDelete } from "../../funcs/destinationsDeleteDestinationDestinationsDestinationIdDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .DeleteDestinationDestinationsDestinationIdDeleteRequest$inboundSchema,
};

export const tool$destinationsDeleteDestinationDestinationsDestinationIdDelete:
  ToolDefinition<typeof args> = {
    name: "destinations-delete-destination-destinations-destination-id-delete",
    description: `Delete Destination

Remove a holiday destination from the database by its ID.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await destinationsDeleteDestinationDestinationsDestinationIdDelete(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
