/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { destinationsCreateDestination } from "../../funcs/destinationsCreateDestination.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.Destination$inboundSchema,
};

export const tool$destinationsCreateDestination: ToolDefinition<typeof args> = {
  name: "destinations-create-destination",
  description: `Create Destination

Add a new holiday destination to the database.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await destinationsCreateDestination(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
