/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { destinationsGetDestinations } from "../../funcs/destinationsGetDestinations.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetDestinationsRequest$inboundSchema,
};

export const tool$destinationsGetDestinations: ToolDefinition<typeof args> = {
  name: "destinations-get-destinations",
  description: `Get Destinations

Retrieve a list of all holiday destinations in the database, optionally filtered by minimum rating.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await destinationsGetDestinations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
