/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { generalReadRootGet } from "../../funcs/generalReadRootGet.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$generalReadRootGet: ToolDefinition = {
  name: "general-read-root-get",
  description: `Read Root

Root endpoint, returns a friendly greeting.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await generalReadRootGet(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
