/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { destinationsCreateDestinationDestinationsPost } from "../funcs/destinationsCreateDestinationDestinationsPost.js";
import { destinationsDeleteDestinationDestinationsDestinationIdDelete } from "../funcs/destinationsDeleteDestinationDestinationsDestinationIdDelete.js";
import { destinationsGetDestinationByIdDestinationsDestinationIdGet } from "../funcs/destinationsGetDestinationByIdDestinationsDestinationIdGet.js";
import { destinationsGetDestinationsDestinationsGet } from "../funcs/destinationsGetDestinationsDestinationsGet.js";
import { destinationsUpdateDestinationDestinationsDestinationIdPut } from "../funcs/destinationsUpdateDestinationDestinationsDestinationIdPut.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Destinations extends ClientSDK {
  /**
   * Get Destinations
   *
   * @remarks
   * Retrieve a list of all holiday destinations in the database, optionally filtered by minimum rating.
   */
  async getDestinationsDestinationsGet(
    request: operations.GetDestinationsDestinationsGetRequest,
    options?: RequestOptions,
  ): Promise<Array<components.Destination>> {
    return unwrapAsync(destinationsGetDestinationsDestinationsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Destination
   *
   * @remarks
   * Add a new holiday destination to the database.
   */
  async createDestinationDestinationsPost(
    request: components.Destination,
    options?: RequestOptions,
  ): Promise<components.Destination> {
    return unwrapAsync(destinationsCreateDestinationDestinationsPost(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Destination
   *
   * @remarks
   * Remove a holiday destination from the database by its ID.
   */
  async deleteDestinationDestinationsDestinationIdDelete(
    request: operations.DeleteDestinationDestinationsDestinationIdDeleteRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      destinationsDeleteDestinationDestinationsDestinationIdDelete(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Get Destination By Id
   *
   * @remarks
   * Retrieve details of a specific holiday destination by its ID.
   */
  async getDestinationByIdDestinationsDestinationIdGet(
    request: operations.GetDestinationByIdDestinationsDestinationIdGetRequest,
    options?: RequestOptions,
  ): Promise<components.Destination> {
    return unwrapAsync(
      destinationsGetDestinationByIdDestinationsDestinationIdGet(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Update Destination
   *
   * @remarks
   * Update details of a specific holiday destination by its ID.
   */
  async updateDestinationDestinationsDestinationIdPut(
    request: operations.UpdateDestinationDestinationsDestinationIdPutRequest,
    options?: RequestOptions,
  ): Promise<components.Destination> {
    return unwrapAsync(
      destinationsUpdateDestinationDestinationsDestinationIdPut(
        this,
        request,
        options,
      ),
    );
  }
}
