/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetDestinationsDestinationsGetRequest = {
  /**
   * Filter destinations by minimum rating (0 to 5).
   */
  minRating?: number | undefined;
};

/** @internal */
export const GetDestinationsDestinationsGetRequest$inboundSchema: z.ZodType<
  GetDestinationsDestinationsGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  min_rating: z.number().default(0),
}).transform((v) => {
  return remap$(v, {
    "min_rating": "minRating",
  });
});

/** @internal */
export type GetDestinationsDestinationsGetRequest$Outbound = {
  min_rating: number;
};

/** @internal */
export const GetDestinationsDestinationsGetRequest$outboundSchema: z.ZodType<
  GetDestinationsDestinationsGetRequest$Outbound,
  z.ZodTypeDef,
  GetDestinationsDestinationsGetRequest
> = z.object({
  minRating: z.number().default(0),
}).transform((v) => {
  return remap$(v, {
    minRating: "min_rating",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDestinationsDestinationsGetRequest$ {
  /** @deprecated use `GetDestinationsDestinationsGetRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetDestinationsDestinationsGetRequest$inboundSchema;
  /** @deprecated use `GetDestinationsDestinationsGetRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetDestinationsDestinationsGetRequest$outboundSchema;
  /** @deprecated use `GetDestinationsDestinationsGetRequest$Outbound` instead. */
  export type Outbound = GetDestinationsDestinationsGetRequest$Outbound;
}

export function getDestinationsDestinationsGetRequestToJSON(
  getDestinationsDestinationsGetRequest: GetDestinationsDestinationsGetRequest,
): string {
  return JSON.stringify(
    GetDestinationsDestinationsGetRequest$outboundSchema.parse(
      getDestinationsDestinationsGetRequest,
    ),
  );
}

export function getDestinationsDestinationsGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetDestinationsDestinationsGetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetDestinationsDestinationsGetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDestinationsDestinationsGetRequest' from JSON`,
  );
}
